version: '3.7'
services:
  frontend:
    build: frontend
    image: acrlearningazure.azurecr.io/frontend
    container_name: frontend-docker
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build: backend
    image: acrlearningazure.azurecr.io/backend
    container_name: backend-docker
